# Generated by Django 6.0.4 on 2026-04-23 01:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_number', models.CharField(max_length=50, unique=True)),
                ('application_name', models.CharField(max_length=255)),
                ('class_numbers', models.CharField(blank=True, max_length=255)),
                ('application_number', models.CharField(blank=True, max_length=100)),
                ('applicant_name', models.CharField(max_length=255)),
                ('trading_as', models.CharField(blank=True, max_length=255)),
                ('applicant_type', models.CharField(choices=[('sole_proprietor', 'Sole Proprietor'), ('company', 'Company')], default='company', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('client_type', models.CharField(choices=[('A', 'A (consultant)'), ('X', 'X (direct client)')], default='X', max_length=1)),
                ('jurisdiction', models.CharField(blank=True, max_length=100)),
                ('current_stage', models.IntegerField(choices=[(1, 'Stage 1: Filing & Examination'), (2, 'Stage 2: Internal Processing'), (3, 'Stage 3: Publication & Demand'), (4, 'Stage 4: Completion')], default=1)),
                ('current_sub_stage', models.CharField(choices=[('filing', 'Filing'), ('ack_received', 'Acknowledgement Received'), ('exam_objection', 'Examination (Objection Raised)'), ('exam_replied', 'Examination Replied'), ('exam_done', 'Examination Done'), ('internal_processing', 'Internal processing / correction / re-filing'), ('published', 'Published in Journal'), ('opposition', 'Opposition Filed'), ('hearing_scheduled', 'Hearing Scheduled'), ('hearing_done', 'Hearing Done'), ('demand_note', 'Demand Note Issued'), ('demand_fee_paid', 'Demand Fee Paid'), ('certificate_issued', 'Certificate Issued'), ('completed', 'Completed / Closed')], default='filing', max_length=50)),
                ('current_status', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='cases.application')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('assignment_added', 'Assignment Added'), ('event_added', 'Event Added')], max_length=30)),
                ('field_changed', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='cases.application')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('logo', 'Logo'), ('certificate', 'Certificate'), ('notice', 'Notice'), ('other', 'Other')], default='other', max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('preview_enabled', models.BooleanField(default=True)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='cases.application')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('filed', 'Filed'), ('ack_received', 'Acknowledgement Received'), ('objection', 'Objection'), ('reply_filed', 'Reply Filed'), ('publication', 'Publication'), ('opposition', 'Opposition'), ('hearing', 'Hearing'), ('demand_note', 'Demand Note'), ('certificate_issued', 'Certificate Issued')], max_length=50)),
                ('event_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('document_link', models.CharField(blank=True, max_length=500)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('stage', models.IntegerField(blank=True, choices=[(1, 'Stage 1: Filing & Examination'), (2, 'Stage 2: Internal Processing'), (3, 'Stage 3: Publication & Demand'), (4, 'Stage 4: Completion')], null=True)),
                ('sub_stage', models.CharField(blank=True, choices=[('filing', 'Filing'), ('ack_received', 'Acknowledgement Received'), ('exam_objection', 'Examination (Objection Raised)'), ('exam_replied', 'Examination Replied'), ('exam_done', 'Examination Done'), ('internal_processing', 'Internal processing / correction / re-filing'), ('published', 'Published in Journal'), ('opposition', 'Opposition Filed'), ('hearing_scheduled', 'Hearing Scheduled'), ('hearing_done', 'Hearing Done'), ('demand_note', 'Demand Note Issued'), ('demand_fee_paid', 'Demand Fee Paid'), ('certificate_issued', 'Certificate Issued'), ('completed', 'Completed / Closed')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='cases.application')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_datetime', '-id'],
            },
        ),
    ]
