# Generated by Django 6.0.4 on 2026-04-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='agent_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='agent_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='application_type',
            field=models.CharField(choices=[('trademark', 'Trademark'), ('copyright', 'Copyright'), ('ntn', 'NTN'), ('company', 'Company')], default='trademark', max_length=30),
        ),
        migrations.AddField(
            model_name='application',
            name='application_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='client_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='dispatch_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='filing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='application',
            name='sequence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='trademark_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='client_type',
            field=models.CharField(choices=[('A', 'A (consultant)'), ('X', 'X (direct client)'), ('N', 'N')], default='X', max_length=1),
        ),
        migrations.AlterField(
            model_name='application',
            name='current_stage',
            field=models.IntegerField(choices=[(1, 'Stage 1: Filing'), (2, 'Stage 2: Examination'), (3, 'Stage 3: Financial / Legal'), (4, 'Stage 4: Completion')], default=1),
        ),
        migrations.AlterField(
            model_name='application',
            name='current_sub_stage',
            field=models.CharField(blank=True, choices=[('filed', 'FILED'), ('ack_received', 'ACKNOWLEDGMENT RECEIVED'), ('examination_done', 'EXAMINATION DONE'), ('acceptance_done', 'ACCEPTANCE DONE'), ('hearing', 'HEARING'), ('demand_note_received', 'DEMAND NOTE RECEIVED'), ('demand_note_submitted', 'DEMAND NOTE SUBMITTED'), ('published', 'PUBLISHED'), ('certificate_received', 'CERTIFICATE RECEIVED'), ('certificate_print', 'CERTIFICATE PRINT'), ('certificate_dispatch', 'CERTIFICATE DISPATCH'), ('opposition_filed', 'OPPOSITION FILED'), ('opposition_received', 'OPPOSITION RECEIVED'), ('opposition_withdrawn', 'OPPOSITION WITHDRAWN'), ('opposition_abandoned', 'OPPOSITION ABANDONED'), ('reactivation_filed', 'REACTIVATION FILED'), ('imported_data', 'IMPORTED DATA'), ('closed', 'CLOSED / ABD / STOP')], max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('filing', 'Filing'), ('objection', 'Objection'), ('publication', 'Publication'), ('demand', 'Demand'), ('certificate', 'Certificate'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='stage',
            field=models.IntegerField(blank=True, choices=[(1, 'Stage 1: Filing'), (2, 'Stage 2: Examination'), (3, 'Stage 3: Financial / Legal'), (4, 'Stage 4: Completion')], null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='sub_stage',
            field=models.CharField(blank=True, choices=[('filed', 'FILED'), ('ack_received', 'ACKNOWLEDGMENT RECEIVED'), ('examination_done', 'EXAMINATION DONE'), ('acceptance_done', 'ACCEPTANCE DONE'), ('hearing', 'HEARING'), ('demand_note_received', 'DEMAND NOTE RECEIVED'), ('demand_note_submitted', 'DEMAND NOTE SUBMITTED'), ('published', 'PUBLISHED'), ('certificate_received', 'CERTIFICATE RECEIVED'), ('certificate_print', 'CERTIFICATE PRINT'), ('certificate_dispatch', 'CERTIFICATE DISPATCH'), ('opposition_filed', 'OPPOSITION FILED'), ('opposition_received', 'OPPOSITION RECEIVED'), ('opposition_withdrawn', 'OPPOSITION WITHDRAWN'), ('opposition_abandoned', 'OPPOSITION ABANDONED'), ('reactivation_filed', 'REACTIVATION FILED'), ('imported_data', 'IMPORTED DATA'), ('closed', 'CLOSED / ABD / STOP')], max_length=50),
        ),
    ]
