# Generated by Django 6.0.4 on 2026-04-23 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_application_agent_address_application_agent_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='IP Case Platform', max_length=255)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logo/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.RemoveField(
            model_name='application',
            name='application_number',
        ),
        migrations.AddField(
            model_name='application',
            name='case_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='Case No'),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant_type',
            field=models.CharField(choices=[('sole_proprietor', 'Sole Proprietor'), ('partner', 'Partner'), ('ceo', 'CEO'), ('company', 'Company')], default='company', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='city',
            field=models.CharField(blank=True, choices=[('Lahore', 'Lahore'), ('Karachi', 'Karachi'), ('Islamabad', 'Islamabad'), ('Peshawar', 'Peshawar')], max_length=50),
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='case_files/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_uploads', to='cases.application')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
