# Generated by Django 6.0.4 on 2026-04-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_sitesettings_remove_application_application_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='folder_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
