# Generated by Django 6.0.4 on 2026-04-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='client_type',
            field=models.CharField(choices=[('A', 'A (consultant)'), ('X', 'X (CLIENTS)'), ('N', 'N (NOOR BAAF)')], default='X', max_length=1),
        ),
    ]
