# Generated by Django 6.0.4 on 2026-04-24 11:42

from django.db import migrations, models


def copy_folder_number_to_case_number(apps, schema_editor):
    """Copy data from folder_number to case_number before removing the old field"""
    Application = apps.get_model('cases', 'Application')
    for app in Application.objects.all():
        if app.folder_number and not app.case_number:
            app.case_number = app.folder_number
            app.save(update_fields=['case_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_alter_application_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='case_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Case #'),
        ),
        migrations.RunPython(copy_folder_number_to_case_number, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='application',
            name='case_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Case #'),
        ),
        migrations.RemoveField(
            model_name='application',
            name='folder_number',
        ),
        migrations.AlterField(
            model_name='application',
            name='case_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='Case No (Official)'),
        ),
    ]
