# Generated by Django 6.0.4 on 2026-04-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_remove_application_folder_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlink',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='documentlink',
            name='file_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
