# Generated by Django 6.0.4 on 2026-04-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_documentlink_file_alter_documentlink_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='event_documents/%Y/%m/'),
        ),
    ]
