# Generated by Django 6.0.4 on 2026-04-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_event_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='folder_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Folder No'),
        ),
    ]
