# Generated by Django 6.0.4 on 2026-04-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_application_folder_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='agent_name',
            field=models.CharField(blank=True, choices=[('Fasial', 'Fasial'), ('Rashid', 'Rashid'), ('Uzma', 'Uzma'), ('Sulman', 'Sulman')], max_length=50),
        ),
    ]
