# Generated by Django 6.0.4 on 2026-04-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_alter_application_agent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='city',
            field=models.CharField(blank=True, choices=[('ISB', 'Islamabad'), ('LHR', 'Lahore'), ('KHI', 'Karachi')], max_length=50),
        ),
    ]
