# Generated by Django 6.0.4 on 2026-04-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_alter_application_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='demand_note_date',
            field=models.DateField(blank=True, null=True, verbose_name='Demand Note Date'),
        ),
    ]
